### ISSUE TITLE
Download link issue

### ISSUE THREAD

**Issue by masudr4n4** [amit-khan/BDTextbooks#1]
Dear @amit-khan can you please  cite the apk link yo the readme file?

**Comment by masudr4n4** [comment]
So that open source contributor like me can test your app.tnx

**Comment by masudr4n4** [comment]
And pls update the app link cause i can not download  the app from your drive link.

**Comment by amit-khan** [comment]
Hello @maaudrana The apk file has been hosted in Dropbox for your convenience. Pls check https://www.dropbox.com/s/3hnoecqeqjc1kmu/BD%20Textbooks.apk?dl=0
